--
-- PostgreSQL database dump
--

\restrict iTSaebiveB5bCwkKOueBRb4V3zpkceMIShc3Q1YW8TawKJCCLUfOetGCmdZjV6M

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: update_vehicle_current_location(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_vehicle_current_location() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    UPDATE public.vehicles
    SET
        current_latitude = NEW.latitude,
        current_longitude = NEW.longitude,
        last_updated = NEW.updated_at
    WHERE id = NEW.vehicle_id;

    RETURN NEW;
END;
$$;


ALTER FUNCTION public.update_vehicle_current_location() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accessibility_info; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accessibility_info (
    id bigint NOT NULL,
    stop_id bigint NOT NULL,
    wheelchair_accessible boolean DEFAULT false,
    ramp_available boolean DEFAULT false,
    elevator_available boolean DEFAULT false,
    tactile_path boolean DEFAULT false,
    audio_announcements boolean DEFAULT false,
    braille_signage boolean DEFAULT false,
    accessible_toilet boolean DEFAULT false,
    accessibility_notes text,
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.accessibility_info OWNER TO postgres;

--
-- Name: accessibility_info_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accessibility_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accessibility_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_users (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(150) NOT NULL,
    phone character varying(20),
    user_type character varying(20) DEFAULT 'passenger'::character varying NOT NULL,
    accessibility_need character varying(50) DEFAULT 'none'::character varying,
    created_at timestamp with time zone DEFAULT now(),
    auth_user_id uuid,
    CONSTRAINT app_users_accessibility_need_check CHECK (((accessibility_need)::text = ANY ((ARRAY['none'::character varying, 'wheelchair'::character varying, 'visually_impaired'::character varying, 'hearing_impaired'::character varying, 'elderly'::character varying, 'other'::character varying])::text[]))),
    CONSTRAINT app_users_user_type_check CHECK (((user_type)::text = ANY ((ARRAY['passenger'::character varying, 'driver'::character varying, 'operator'::character varying, 'admin'::character varying])::text[])))
);


ALTER TABLE public.app_users OWNER TO postgres;

--
-- Name: app_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: drivers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drivers (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    vehicle_id bigint,
    license_number character varying(50),
    is_available boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.drivers OWNER TO postgres;

--
-- Name: drivers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.drivers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.drivers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emergency_contacts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.emergency_contacts (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    relationship character varying(50),
    phone character varying(20) NOT NULL,
    is_primary boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.emergency_contacts OWNER TO postgres;

--
-- Name: emergency_contacts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.emergency_contacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emergency_contacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    title character varying(200) NOT NULL,
    message text NOT NULL,
    notification_type character varying(40),
    is_read boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT notifications_notification_type_check CHECK (((notification_type)::text = ANY ((ARRAY['arrival'::character varying, 'delay'::character varying, 'route_change'::character varying, 'safety'::character varying, 'emergency'::character varying, 'general'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reports (
    id bigint NOT NULL,
    user_id bigint,
    route_id bigint,
    vehicle_id bigint,
    stop_id bigint,
    report_type character varying(30) NOT NULL,
    report_value character varying(100),
    description text,
    latitude double precision,
    longitude double precision,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT reports_report_type_check CHECK (((report_type)::text = ANY ((ARRAY['crowding'::character varying, 'delay'::character varying, 'availability'::character varying, 'safety'::character varying, 'accessibility'::character varying, 'route_issue'::character varying, 'other'::character varying])::text[])))
);


ALTER TABLE public.reports OWNER TO postgres;

--
-- Name: reports_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: route_changes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.route_changes (
    id bigint NOT NULL,
    route_id bigint NOT NULL,
    change_type character varying(30),
    description text NOT NULL,
    start_time timestamp with time zone,
    end_time timestamp with time zone,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT route_changes_change_type_check CHECK (((change_type)::text = ANY ((ARRAY['delay'::character varying, 'diversion'::character varying, 'stop_closed'::character varying, 'route_closed'::character varying, 'schedule_change'::character varying])::text[])))
);


ALTER TABLE public.route_changes OWNER TO postgres;

--
-- Name: route_changes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.route_changes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.route_changes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: route_stops; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.route_stops (
    id bigint NOT NULL,
    route_id bigint NOT NULL,
    stop_id bigint NOT NULL,
    stop_order integer NOT NULL,
    estimated_arrival_minutes integer
);


ALTER TABLE public.route_stops OWNER TO postgres;

--
-- Name: route_stops_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.route_stops ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.route_stops_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: routes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.routes (
    id bigint NOT NULL,
    route_number character varying(30) NOT NULL,
    route_name character varying(150) NOT NULL,
    transport_type character varying(30) NOT NULL,
    description text,
    start_point character varying(150),
    end_point character varying(150),
    estimated_duration_minutes integer,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT routes_transport_type_check CHECK (((transport_type)::text = ANY ((ARRAY['bus'::character varying, 'campus_vehicle'::character varying, 'shuttle'::character varying, 'shared_transport'::character varying])::text[])))
);


ALTER TABLE public.routes OWNER TO postgres;

--
-- Name: routes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.routes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.routes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stops; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stops (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    description text,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    wheelchair_accessible boolean DEFAULT false,
    lighting_level character varying(20) DEFAULT 'medium'::character varying,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT stops_lighting_level_check CHECK (((lighting_level)::text = ANY ((ARRAY['poor'::character varying, 'medium'::character varying, 'good'::character varying])::text[])))
);


ALTER TABLE public.stops OWNER TO postgres;

--
-- Name: stops_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.stops ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stops_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trips; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trips (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    route_id bigint,
    start_stop_id bigint,
    destination_stop_id bigint,
    start_latitude double precision,
    start_longitude double precision,
    destination_latitude double precision,
    destination_longitude double precision,
    start_time timestamp with time zone,
    expected_arrival timestamp with time zone,
    actual_arrival timestamp with time zone,
    status character varying(30) DEFAULT 'planned'::character varying,
    safety_check_in boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT trips_status_check CHECK (((status)::text = ANY ((ARRAY['planned'::character varying, 'active'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'emergency'::character varying])::text[])))
);


ALTER TABLE public.trips OWNER TO postgres;

--
-- Name: trips_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trips ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trips_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicle_locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vehicle_locations (
    vehicle_id bigint NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.vehicle_locations OWNER TO postgres;

--
-- Name: vehicles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vehicles (
    id bigint NOT NULL,
    vehicle_number character varying(50) NOT NULL,
    vehicle_type character varying(30) NOT NULL,
    route_id bigint,
    wheelchair_accessible boolean DEFAULT false,
    wheelchair_capacity integer DEFAULT 0,
    current_latitude double precision,
    current_longitude double precision,
    status character varying(30) DEFAULT 'available'::character varying,
    capacity integer DEFAULT 40,
    current_occupancy integer DEFAULT 0,
    last_updated timestamp with time zone DEFAULT now(),
    driver_id bigint,
    CONSTRAINT vehicles_status_check CHECK (((status)::text = ANY ((ARRAY['available'::character varying, 'on_route'::character varying, 'delayed'::character varying, 'maintenance'::character varying, 'offline'::character varying])::text[]))),
    CONSTRAINT vehicles_vehicle_type_check CHECK (((vehicle_type)::text = ANY ((ARRAY['bus'::character varying, 'shuttle'::character varying, 'campus_vehicle'::character varying, 'shared_vehicle'::character varying])::text[])))
);


ALTER TABLE public.vehicles OWNER TO postgres;

--
-- Name: vehicles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vehicles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accessibility_info; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accessibility_info (id, stop_id, wheelchair_accessible, ramp_available, elevator_available, tactile_path, audio_announcements, braille_signage, accessible_toilet, accessibility_notes, updated_at) FROM stdin;
1	1	t	t	f	t	t	t	f	Main gate has accessible entry and ramp access.	2026-08-20 19:29:06.665254+00
2	2	t	t	f	t	t	f	f	DTS bus stop with accessible boarding area.	2026-08-20 19:29:06.665254+00
3	3	t	t	f	t	f	f	f	Ramp available; tactile guidance can be improved.	2026-08-20 19:29:06.665254+00
4	4	t	t	f	t	t	t	f	Major transport interchange with accessibility facilities.	2026-08-20 19:29:06.665254+00
5	5	t	t	f	t	t	t	f	Major public transport interchange in Patia.	2026-08-20 19:29:06.665254+00
6	6	t	t	t	t	t	t	t	Hospital access with facilities suitable for mobility-impaired passengers.	2026-08-20 19:29:06.665254+00
7	7	t	t	f	t	f	f	f	Accessible campus transport connection.	2026-08-20 19:29:06.665254+00
8	8	f	f	f	f	f	f	f	Accessibility facilities require improvement.	2026-08-20 19:29:06.665254+00
\.


--
-- Data for Name: app_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_users (id, name, email, phone, user_type, accessibility_need, created_at, auth_user_id) FROM stdin;
1	Rahul Sharma	rahul@example.com	9876543210	passenger	none	2026-08-20 19:15:10.503152+00	\N
2	Priya Singh	priya@example.com	9876543211	passenger	wheelchair	2026-08-20 19:15:10.503152+00	\N
3	Amit Kumar	amit@example.com	9876543212	passenger	visually_impaired	2026-08-20 19:15:10.503152+00	\N
4	Rohan Das	rohan@example.com	9876543213	passenger	elderly	2026-08-20 19:15:10.503152+00	\N
6	Transport Admin	admin@example.com	9876543215	admin	none	2026-08-20 19:15:10.503152+00	\N
5	Suresh Driver	suresh@example.com	9876543214	driver	none	2026-08-20 19:15:10.503152+00	6c551953-fc8a-4033-bb26-5511ed2aa04f
\.


--
-- Data for Name: drivers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.drivers (id, user_id, vehicle_id, license_number, is_available, created_at) FROM stdin;
1	5	1	DL-OD-2026-001	t	2026-08-20 19:50:25.180432+00
\.


--
-- Data for Name: emergency_contacts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.emergency_contacts (id, user_id, name, relationship, phone, is_primary, created_at) FROM stdin;
1	1	Mrs. Sharma	Mother	9876500001	t	2026-08-20 19:19:13.539401+00
2	1	Mr. Sharma	Father	9876500002	f	2026-08-20 19:19:13.539401+00
3	2	Anita Singh	Mother	9876500003	t	2026-08-20 19:19:13.539401+00
4	3	Vikram Kumar	Brother	9876500004	t	2026-08-20 19:19:13.539401+00
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (id, user_id, title, message, notification_type, is_read, created_at) FROM stdin;
1	1	Bus Delay	Route R1 is currently experiencing a minor delay.	delay	f	2026-08-20 19:54:48.894683+00
2	2	Accessible Route	An accessible route to Patia Square is available.	general	f	2026-08-20 19:54:48.894683+00
3	3	Crowding Alert	Route R1 is currently reporting high crowding.	arrival	f	2026-08-20 19:54:48.894683+00
4	4	Safety Check-in	Your trip safety check-in has been activated.	safety	f	2026-08-20 19:54:48.894683+00
\.


--
-- Data for Name: reports; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reports (id, user_id, route_id, vehicle_id, stop_id, report_type, report_value, description, latitude, longitude, created_at) FROM stdin;
1	1	1	1	2	crowding	medium	Bus has moderate crowding.	20.3536875	85.8183738	2026-08-20 19:51:43.193773+00
2	2	1	1	4	crowding	high	Bus is almost full.	20.3534	85.8268	2026-08-20 19:51:43.193773+00
3	3	4	2	5	delay	10 minutes	Bus is running approximately 10 minutes late.	20.3547	85.8249	2026-08-20 19:51:43.193773+00
4	4	3	3	6	accessibility	ramp_available	Accessible ramp was successfully used.	20.3517	85.8195	2026-08-20 19:51:43.193773+00
5	1	2	4	3	safety	safe	Area appears well lit and safe.	20.353737	85.8196043	2026-08-20 19:51:43.193773+00
\.


--
-- Data for Name: route_changes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.route_changes (id, route_id, change_type, description, start_time, end_time, is_active, created_at) FROM stdin;
1	1	delay	Route R1 is delayed by approximately 10 minutes due to traffic.	2026-08-20 19:55:39.267265+00	2026-08-20 21:55:39.267265+00	t	2026-08-20 19:55:39.267265+00
2	3	schedule_change	Next shuttle departure has been delayed by 15 minutes.	2026-08-20 19:55:39.267265+00	2026-08-20 22:55:39.267265+00	t	2026-08-20 19:55:39.267265+00
\.


--
-- Data for Name: route_stops; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.route_stops (id, route_id, stop_id, stop_order, estimated_arrival_minutes) FROM stdin;
1	1	1	1	0
2	1	4	2	7
3	1	5	3	15
4	2	1	1	0
5	2	2	2	5
6	2	3	3	10
7	2	4	4	15
8	3	1	1	0
9	3	2	2	7
10	3	6	3	15
11	4	1	1	0
12	4	3	2	10
13	4	4	3	18
14	4	5	4	25
\.


--
-- Data for Name: routes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.routes (id, route_number, route_name, transport_type, description, start_point, end_point, estimated_duration_minutes, is_active, created_at) FROM stdin;
1	R1	KIIT to Patia	bus	Public transport connection between KIIT and Patia.	KIIT Main Gate	Patia Square	15	t	2026-08-20 19:30:52.113036+00
2	R2	KIIT Campus Circular	campus_vehicle	Internal campus shuttle connecting major KIIT locations.	KIIT Main Gate	KIIT Main Gate	20	t	2026-08-20 19:30:52.113036+00
3	R3	KIIT to KIMS	shuttle	Accessible shuttle connection between KIIT and KIMS Hospital.	KIIT Main Gate	KIMS Hospital	15	t	2026-08-20 19:30:52.113036+00
4	R4	KIIT to City Connection	bus	Public transport connection from KIIT towards the city.	KIIT Main Gate	Patia Square	25	t	2026-08-20 19:30:52.113036+00
\.


--
-- Data for Name: stops; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stops (id, name, description, latitude, longitude, wheelchair_accessible, lighting_level, is_active, created_at) FROM stdin;
1	KIIT Main Gate	Main KIIT campus entrance and transport access point	20.35349	85.81928	t	good	t	2026-08-20 19:26:19.125162+00
2	KIIT DTS Bus Stop	DTS bus stop on Shikhar Chandi Road	20.3536875	85.8183738	t	good	t	2026-08-20 19:26:19.125162+00
3	KIIT Local Bus Stand 2	KIIT local bus stand on Shikhar Chandi Road	20.353737	85.8196043	t	good	t	2026-08-20 19:26:19.125162+00
4	KIIT Square	Major transport interchange near KIIT	20.3534	85.8268	t	good	t	2026-08-20 19:26:19.125162+00
5	Patia Square	Major public transport interchange in Patia	20.3547	85.8249	t	good	t	2026-08-20 19:26:19.125162+00
6	KIMS Hospital	Transport access near KIMS Hospital	20.3517	85.8195	t	good	t	2026-08-20 19:26:19.125162+00
7	Koel Campus	Transport stop serving KIIT Koel Campus	20.3498	85.8188	t	good	t	2026-08-20 19:26:19.125162+00
8	Shikharchandi Vihar	Public transport stop near Shikharchandi Vihar	20.362	85.824	f	medium	t	2026-08-20 19:26:19.125162+00
\.


--
-- Data for Name: trips; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trips (id, user_id, route_id, start_stop_id, destination_stop_id, start_latitude, start_longitude, destination_latitude, destination_longitude, start_time, expected_arrival, actual_arrival, status, safety_check_in, created_at) FROM stdin;
1	1	1	1	5	20.35349	85.81928	20.3547	85.8249	2026-08-20 19:53:44.023409+00	2026-08-20 20:08:44.023409+00	\N	active	t	2026-08-20 19:53:44.023409+00
\.


--
-- Data for Name: vehicle_locations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.vehicle_locations (vehicle_id, latitude, longitude, updated_at) FROM stdin;
1	20.354	85.8195	2026-08-21 07:48:07.571332+00
\.


--
-- Data for Name: vehicles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.vehicles (id, vehicle_number, vehicle_type, route_id, wheelchair_accessible, wheelchair_capacity, current_latitude, current_longitude, status, capacity, current_occupancy, last_updated, driver_id) FROM stdin;
2	BUS-102	bus	4	t	2	20.355	85.823	on_route	45	40	2026-08-20 19:49:31.010946+00	\N
3	SHUTTLE-201	shuttle	3	t	2	20.354	85.819	available	20	8	2026-08-20 19:49:31.010946+00	\N
4	CAMPUS-301	campus_vehicle	2	t	1	20.3537	85.8196	on_route	25	12	2026-08-20 19:49:31.010946+00	\N
1	BUS-101	bus	1	t	2	20.3542	85.821	on_route	50	32	2026-08-20 19:49:31.010946+00	5
\.


--
-- Name: accessibility_info_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accessibility_info_id_seq', 8, true);


--
-- Name: app_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.app_users_id_seq', 6, true);


--
-- Name: drivers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.drivers_id_seq', 1, true);


--
-- Name: emergency_contacts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.emergency_contacts_id_seq', 4, true);


--
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notifications_id_seq', 4, true);


--
-- Name: reports_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reports_id_seq', 5, true);


--
-- Name: route_changes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.route_changes_id_seq', 2, true);


--
-- Name: route_stops_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.route_stops_id_seq', 14, true);


--
-- Name: routes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.routes_id_seq', 4, true);


--
-- Name: stops_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.stops_id_seq', 8, true);


--
-- Name: trips_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trips_id_seq', 1, true);


--
-- Name: vehicles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.vehicles_id_seq', 4, true);


--
-- Name: accessibility_info accessibility_info_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accessibility_info
    ADD CONSTRAINT accessibility_info_pkey PRIMARY KEY (id);


--
-- Name: accessibility_info accessibility_info_stop_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accessibility_info
    ADD CONSTRAINT accessibility_info_stop_id_key UNIQUE (stop_id);


--
-- Name: app_users app_users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_email_key UNIQUE (email);


--
-- Name: app_users app_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);


--
-- Name: drivers drivers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT drivers_pkey PRIMARY KEY (id);


--
-- Name: drivers drivers_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT drivers_user_id_key UNIQUE (user_id);


--
-- Name: emergency_contacts emergency_contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emergency_contacts
    ADD CONSTRAINT emergency_contacts_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: reports reports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_pkey PRIMARY KEY (id);


--
-- Name: route_changes route_changes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_changes
    ADD CONSTRAINT route_changes_pkey PRIMARY KEY (id);


--
-- Name: route_stops route_stops_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_stops
    ADD CONSTRAINT route_stops_pkey PRIMARY KEY (id);


--
-- Name: route_stops route_stops_route_id_stop_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_stops
    ADD CONSTRAINT route_stops_route_id_stop_id_key UNIQUE (route_id, stop_id);


--
-- Name: route_stops route_stops_route_id_stop_order_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_stops
    ADD CONSTRAINT route_stops_route_id_stop_order_key UNIQUE (route_id, stop_order);


--
-- Name: routes routes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.routes
    ADD CONSTRAINT routes_pkey PRIMARY KEY (id);


--
-- Name: stops stops_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stops
    ADD CONSTRAINT stops_pkey PRIMARY KEY (id);


--
-- Name: trips trips_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_pkey PRIMARY KEY (id);


--
-- Name: vehicle_locations vehicle_locations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicle_locations
    ADD CONSTRAINT vehicle_locations_pkey PRIMARY KEY (vehicle_id);


--
-- Name: vehicles vehicles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_pkey PRIMARY KEY (id);


--
-- Name: vehicles vehicles_vehicle_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_vehicle_number_key UNIQUE (vehicle_number);


--
-- Name: idx_emergency_contacts_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_emergency_contacts_user ON public.emergency_contacts USING btree (user_id);


--
-- Name: idx_notifications_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notifications_user ON public.notifications USING btree (user_id);


--
-- Name: idx_reports_created; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_reports_created ON public.reports USING btree (created_at);


--
-- Name: idx_reports_route; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_reports_route ON public.reports USING btree (route_id);


--
-- Name: idx_reports_stop; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_reports_stop ON public.reports USING btree (stop_id);


--
-- Name: idx_reports_vehicle; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_reports_vehicle ON public.reports USING btree (vehicle_id);


--
-- Name: idx_route_changes_route; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_route_changes_route ON public.route_changes USING btree (route_id);


--
-- Name: idx_route_stops_route; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_route_stops_route ON public.route_stops USING btree (route_id);


--
-- Name: idx_route_stops_stop; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_route_stops_stop ON public.route_stops USING btree (stop_id);


--
-- Name: idx_trips_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_trips_user ON public.trips USING btree (user_id);


--
-- Name: idx_vehicles_route; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_vehicles_route ON public.vehicles USING btree (route_id);


--
-- Name: accessibility_info accessibility_info_stop_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accessibility_info
    ADD CONSTRAINT accessibility_info_stop_id_fkey FOREIGN KEY (stop_id) REFERENCES public.stops(id) ON DELETE CASCADE;


--
-- Name: drivers drivers_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT drivers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id) ON DELETE CASCADE;


--
-- Name: drivers drivers_vehicle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT drivers_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE SET NULL;


--
-- Name: emergency_contacts emergency_contacts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emergency_contacts
    ADD CONSTRAINT emergency_contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id) ON DELETE CASCADE;


--
-- Name: notifications notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id) ON DELETE CASCADE;


--
-- Name: reports reports_route_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id) ON DELETE SET NULL;


--
-- Name: reports reports_stop_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_stop_id_fkey FOREIGN KEY (stop_id) REFERENCES public.stops(id) ON DELETE SET NULL;


--
-- Name: reports reports_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id) ON DELETE SET NULL;


--
-- Name: reports reports_vehicle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE SET NULL;


--
-- Name: route_changes route_changes_route_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_changes
    ADD CONSTRAINT route_changes_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id) ON DELETE CASCADE;


--
-- Name: route_stops route_stops_route_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_stops
    ADD CONSTRAINT route_stops_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id) ON DELETE CASCADE;


--
-- Name: route_stops route_stops_stop_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_stops
    ADD CONSTRAINT route_stops_stop_id_fkey FOREIGN KEY (stop_id) REFERENCES public.stops(id) ON DELETE CASCADE;


--
-- Name: trips trips_destination_stop_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_destination_stop_id_fkey FOREIGN KEY (destination_stop_id) REFERENCES public.stops(id) ON DELETE SET NULL;


--
-- Name: trips trips_route_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id) ON DELETE SET NULL;


--
-- Name: trips trips_start_stop_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_start_stop_id_fkey FOREIGN KEY (start_stop_id) REFERENCES public.stops(id) ON DELETE SET NULL;


--
-- Name: trips trips_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id) ON DELETE CASCADE;


--
-- Name: vehicle_locations vehicle_locations_vehicle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicle_locations
    ADD CONSTRAINT vehicle_locations_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE CASCADE;


--
-- Name: vehicles vehicles_driver_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.app_users(id);


--
-- Name: vehicles vehicles_route_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id) ON DELETE SET NULL;


--
-- Name: accessibility_info Allow public read access to accessibility info; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow public read access to accessibility info" ON public.accessibility_info FOR SELECT TO authenticated, anon USING (true);


--
-- Name: route_stops Allow public read access to route stops; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow public read access to route stops" ON public.route_stops FOR SELECT TO authenticated, anon USING (true);


--
-- Name: vehicle_locations Anyone can read vehicle locations; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Anyone can read vehicle locations" ON public.vehicle_locations FOR SELECT TO authenticated, anon USING (true);


--
-- Name: vehicle_locations Authenticated users can insert vehicle locations; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Authenticated users can insert vehicle locations" ON public.vehicle_locations FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: vehicle_locations Drivers can update their assigned vehicle location; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Drivers can update their assigned vehicle location" ON public.vehicle_locations FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1
   FROM (public.vehicles v
     JOIN public.app_users au ON ((au.id = v.driver_id)))
  WHERE ((v.id = vehicle_locations.vehicle_id) AND (au.auth_user_id = auth.uid()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM (public.vehicles v
     JOIN public.app_users au ON ((au.id = v.driver_id)))
  WHERE ((v.id = vehicle_locations.vehicle_id) AND (au.auth_user_id = auth.uid())))));


--
-- Name: route_stops; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.route_stops ENABLE ROW LEVEL SECURITY;

--
-- Name: vehicle_locations; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.vehicle_locations ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: TABLE accessibility_info; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.accessibility_info TO anon;
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.accessibility_info TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.accessibility_info TO service_role;


--
-- Name: TABLE app_users; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.app_users TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.app_users TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.app_users TO service_role;


--
-- Name: TABLE drivers; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.drivers TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.drivers TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.drivers TO service_role;


--
-- Name: TABLE emergency_contacts; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.emergency_contacts TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.emergency_contacts TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.emergency_contacts TO service_role;


--
-- Name: TABLE notifications; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.notifications TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.notifications TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.notifications TO service_role;


--
-- Name: TABLE reports; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.reports TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.reports TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.reports TO service_role;


--
-- Name: TABLE route_changes; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.route_changes TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.route_changes TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.route_changes TO service_role;


--
-- Name: TABLE route_stops; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.route_stops TO anon;
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.route_stops TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.route_stops TO service_role;


--
-- Name: TABLE routes; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.routes TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.routes TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.routes TO service_role;


--
-- Name: TABLE stops; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.stops TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.stops TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.stops TO service_role;


--
-- Name: TABLE trips; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.trips TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.trips TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.trips TO service_role;


--
-- Name: TABLE vehicle_locations; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.vehicle_locations TO anon;
GRANT SELECT,INSERT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE public.vehicle_locations TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.vehicle_locations TO service_role;


--
-- Name: TABLE vehicles; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.vehicles TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.vehicles TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.vehicles TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--

\unrestrict iTSaebiveB5bCwkKOueBRb4V3zpkceMIShc3Q1YW8TawKJCCLUfOetGCmdZjV6M

